Kolmakov
study-17-09/homeworks pull request #16
Opened 2020-11-12 15:36 UTC by Cerne13

Поменял ссылки на страницу с домашками и фото, добавил свою папку, сделал первые 4 пункта ДЗ (остальное к, сожалению, еще не успел).

2020-11-13 09:57 UTC, froz-ferre requested changes

2020-11-13 09:57 UTC, froz-ferre commented on Kolmakov/05.11.20/04_array_elem_sum.html
> +            theArr.push(parseFloat(thePrompt));
Если пользователь вводит строку, в которой невозможно спарсить number - такую строку нужно игнорировать (не добавлять в массив)

2020-11-13 09:57 UTC, froz-ferre commented on Kolmakov/05.11.20/04_array_elem_sum.html
> +          alert(`В массиве находится ${theArr.length} элементов.`);
Пользователю нужно показать не количество введенных данных, а сумму всех элементов. ([Array.prototype.reduce](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce))

2020-11-13 09:57 UTC, froz-ferre commented on Kolmakov/index.html
> +    <h3><a href="05.11.20/" target="blank">05.11.20</a></h3>
Не все сервера поддерживают . в названии каталогов. Лучше ограничиться символами [a-z0-9\-\_]

2020-11-16 16:57 UTC, Cerne13 reviewed
Поправил ошибки, доделал все пункты домашки (кроме 2*).

2020-11-23 08:59 UTC, froz-ferre approved these changes

2020-11-23 08:59 UTC, froz-ferre commented on Kolmakov/05_11_20/05_rand_num_arr.html
> +      })(someNum);
Для чего тут нужна функция?

2020-11-23 08:59 UTC, froz-ferre commented on Kolmakov/11_11_20_objects/02_proto.js
> +// По идее, прямое обращение к head должно быть быстрее. Но на практике получается одинаково. Возможно, интерпретатор при первом прохождении по коду назначает прото-свойство, и при выполнении оно счи
Как Вы проверяли?

2020-11-23 08:59 UTC, froz-ferre commented on Kolmakov/11_11_20_objects/03_clock.js
> +let count = 0;
Перенесите count в Clock

2020-11-23 08:59 UTC, froz-ferre commented on Kolmakov/11_11_20_objects/03_clock.js
> +let ExtendedClock = new Clock();
Тут должно быть наследование

2020-11-23 08:59 UTC, froz-ferre commented on Kolmakov/11_11_20_objects/03_clock.js
> +  this.stop = function () {
Метод должен останавливать таймер.
setInterval возвращает id таймера, который в дальнейшем может быть завершен методом `clearInterval(intervalId)`

2020-11-23 09:27 UTC, froz-ferre approved these changes

2020-11-23 09:39 UTC, merged

2020-11-23 10:01 UTC, Cerne13 commented on Kolmakov/11_11_20_objects/02_proto.js
> +// По идее, прямое обращение к head должно быть быстрее. Но на практике получается одинаково. Возможно, интерпретатор при первом прохождении по коду назначает прото-свойство, и при выполнении оно счи
Я просто в IDE, в консоли смотрел время выполнения, запуская оба варианта несколько раз. В обоих случаях время выполнения колебалось от 0.085 до 0.096 секунд. Могу только предположить, что при большем объеме работы и более сложной логике разница была бы заметна.