Gritsev 02 js objects
study-17-09/homeworks pull request #26
Opened 2020-11-19 19:57 UTC by clayber

Есть вопросы по 3му заданию - не всё адекватно работает.

2020-11-22 23:05 UTC, froz-ferre requested changes

2020-11-22 23:05 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +    this._Start = setInterval(function(){
// !!!!!не понимаю, почему запускается метод Старт родителя
Потому что вы запускаете интервал при создании объекта, а не присваиваете метод свойству this._Start
// и потом не останавливается????
Потому что нет кода, который останавливает этот интервал

2020-11-22 23:05 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
Какие аргументы принимает метод setInterval и за что они отвечают?

2020-11-22 23:05 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +
Где наследственность?

2020-11-24 21:04 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +
Видимо я совсем не понял задания - не понимаю сколько объектов часов должно быть создано один при каждом нажатии на Старт, или должен создаваться каждую секунду новый объект во время исполнения функции setInterval ...

2020-11-24 21:04 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
Никакие не принимает. Функция setInterval - свойство метода.

2020-11-24 21:04 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +    this._Start = setInterval(function(){
Насколько я понял - у нас должно быть множество объектов часов, поэтому и создаю объект на каждом интервале.
В функции Clock я создавал метод
this._Stop = setTimeout(() => {clearInterval(this.Start); console.log("Stop");}, 10000);
для остановки часов.

2020-11-24 21:05 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +function createNewObj(item){
Переделал:
let calculate = function(){return 2+2};
let newobj = createNewObj(myObj, 1+ 0, 'string', calculate);

function createNewObj(myObj, ...arguments){

2020-11-24 21:14 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +
Разве метод -  Clock.apply(this);
не отвечает за наследственность...
Видимо я не понимаю, мы должны унаследовать функцию Clock или какой-то конкретный объект...

2020-11-24 21:21 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
внутри функции  setInterval есть отдельная функция, которая каждую секунду создаёт объекты Часы. Видимо я не понял с объектами, и их не нужно создавать каждую секунду, а нужно создать один раз?

2020-11-24 21:22 UTC, clayber commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
В задании было так:
"Так же добавьте метод count который будет возвращать количество созданных объектов-часов."

2020-11-30 09:22 UTC, froz-ferre requested changes

2020-11-30 09:22 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +    this._Start = setInterval(function(){
У нас должно быть 2 объекта для конструктора Clock и ExtendedClock. Так же у нас должна быть возможность создавать неограниченное количество объектов, все это при помощи оператора new и функции-конструктора.

2020-11-30 09:22 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
> Никакие не принимает. Функция setInterval - свойство метода.

Неверно. [смотрите документацию](https://developer.mozilla.org/ru/docs/Web/API/WindowOrWorkerGlobalScope/setInterval)

2020-11-30 09:22 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +    },console.log("Start"), 1000);
> внутри функции setInterval есть отдельная функция, которая каждую секунду создаёт объекты Часы. Видимо я не понял с объектами, и их не нужно создавать каждую секунду, а нужно создать один раз?

Верно. Объект создается при вызове const clock = new Clock();
Таймер запускается при вызове метода clock.start();
Таймер останавливается при вызове clock.stop();

2020-11-30 09:22 UTC, froz-ferre commented on Gritsev/02_JS_Objects/main.js
> +
Скинул в личку ссылки.
Должно быть 2 объекта, созданных функцией-конструктором.
Так же должно быть реализовано прототипное наследование. Класс ExtendedClock наследуется от Clock

2020-12-16 18:37 UTC, closed without merging